### ISSUE TITLE
希望移除udp重放攻击

### ISSUE THREAD

**Issue by LittleTurtle2333** [imengyu/JiYuTrainer#5]
我们学校很多人使用这个软件，一旦玩起来，全校没法上课。

**Comment by LittleTurtle2333** [comment]
本来cli就可能防止那些不会命令的人，而且普通人也找不到

**Comment by LittleTurtle2333** [comment]
图形化一公布，后果可能不堪设想

**Comment by LittleTurtle2333** [comment]
如果说jiyutrainer能屏蔽udp包，但这不就导致于被整过的人也使用jiyutrainer屏蔽，然后发现这个功能，然后也加入战斗，这是恶性循环

**Comment by LittleTurtle2333** [comment]
本来这个软件防的是教师端，免受教师端的打扰，结果跑偏了搞个对付学生端，有些人自己不听课也就算了，等下还去影响别人听课的。

**Comment by LinWhite2333** [comment]
赞同，加这功能全班天天拿聊天功能对线，还找不到人或者就互相关机玩，课都不用上了

**Comment by imengyu** [comment]
行。这个功能就不要了

**Comment by LittleTurtle2333** [comment]
有cli就够了，门槛低了容易出问题

**Comment by imengyu** [comment]
已经移除
