### ISSUE TITLE
你好，我正在做我自己的极域防控软件，可以在其中附带你的这个程序的发行版吗

### ISSUE THREAD

**Issue by yangshunhuai** [imengyu/JiYuTrainer#9]
我自己的软件主页在[这里](https://github.com/yangshunhuai/StudentMainManager)，希望加入你的JiYuTrainer软件作为备用功能，看到你有MIT License，理论上是允许了这种形式的发行，但是还是希望征得原作者的同意。
附注：我的软件将会按照Apache-2.0 License。

**Comment by imengyu** [comment]
可以的哦

**Comment by yangshunhuai** [comment]
谢谢！
我的这个程序基本部分已经完成了，也可以来[看看](https://github.com/yangshunhuai/StudentMainManager)。

**Comment by LWM480905182** [comment]
很不错
